/*****************************************************************************
 *
 * This file is part of Mapnik (c++ mapping toolkit)
 *
 * Copyright (C) 2012 Artem Pavlenko
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *****************************************************************************/

#include "tags.hpp"

// boost
#include <boost/assign/list_of.hpp>
#include <boost/bimap.hpp>

namespace  mapnik { namespace tags {

typedef boost::bimap<tag_type, name_type> tag_lookup_type;

static const tag_lookup_type tag_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"access")
    (1,"addr:housename")
    (2,"addr:housenumber")
    (3,"addr:interpolation")
    (4,"admin_level")
    (5,"aerialway")
    (6,"aeroway")
    (7 ,"amenity")
    (8 ,"area")
    (9 ,"barrier")
    (10 ,"bicycle")
    (11 ,"brand")
    (12 ,"bridge")
    (13 ,"boundary")
    (14 ,"building")
    (15 ,"construction")
    (16 ,"covered")
    (17 ,"culvert")
    (18 ,"cutting")
    (19 ,"denomination")
    (20 ,"disused")
    (21 ,"embankment")
    (22 ,"foot")
    (23 ,"generator:source")
    (24 ,"harbour")
    (25 ,"highway")
    (26 ,"historic")
    (27 ,"horse")
    (28 ,"intermittent")
    (29 ,"junction")
    (30 ,"landuse")
    (31 ,"layer")
    (32 ,"leisure")
    (33 ,"lock")
    (34 ,"man_made")
    (35 ,"military")
    (36 ,"motorcar")
    (37 ,"name")
    (38 ,"natural")
    (39 ,"oneway")
    (40 ,"operator")
    (41 ,"population")
    (42 ,"power")
    (43 ,"power_source")
    (44 ,"place")
    (45 ,"railway")
    (46 ,"ref")
    (47 ,"religion")
    (48 ,"route")
    (49 ,"service")
    (50 ,"shop")
    (51 ,"sport")
    (52 ,"surface")
    (53 ,"toll")
    (54 ,"tourism")
    (55 ,"tower:type")
    (56 ,"tracktype")
    (57 ,"tunnel")
    (58 ,"water")
    (59 ,"waterway")
    (60 ,"wetland")
    (61 ,"width")
    (62 ,"wood")
    ;

static const tag_lookup_type tag_value_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"building=yes")
    (1,"highway=residential")
    (2,"highway=service")
    (3,"waterway=stream")
    (4,"highway=unclassified")
    (5,"highway=track")
    (6,"oneway=yes")
    (7,"natural=water")
    (8,"highway=footway")
    (9,"access=private")
    (10,"highway=tertiary")
    (11,"highway=path")
    (12,"highway=secondary")
    (13,"landuse=forest")
    (14,"bridge=yes")
    (15,"natural=tree")
    (16,"surface=paved")
    (17,"natural=wood")
    (18,"highway=primary")
    (19,"landuse=grass")
    (20,"landuse=residential")
    (21,"surface=unpaved")
    (22,"highway=bus_stop")
    (23,"surface=asphalt")
    (24,"bicycle=yes")
    (25,"amenity=parking")
    (26,"place=locality")
    (27,"railway=rail")
    (28,"service=parking_aisle")
    (29,"boundary=administrative")
    (30,"building=house")
    (31,"place=village")
    (32,"natural=coastline")
    (33,"tracktype=grade2")
    (34,"oneway=no")
    (35,"service=driveway")
    (36,"highway=turning_circle")
    (37,"place=hamlet")
    (38,"natural=wetland")
    (39,"tracktype=grade3")
    (40,"waterway=river")
    (41,"highway=cycleway")
    (42,"barrier=fence")
    (43,"building=residential")
    (44,"amenity=school")
    (45,"highway=crossing")
    (46,"admin_level=8")
    (47,"highway=trunk")
    (49,"amenity=place_of_worship")
    (50,"landuse=farmland")
    (51,"tracktype=grade1")
    (52,"highway=road")
    (53,"landuse=farm")
    (54,"surface=gravel")
    (55,"landuse=meadow")
    (56,"highway=motorway")
    (57,"highway=traffic_signals")
    (58,"building=hut")
    (59,"highway=motorway_link")
    (60,"tracktype=grade4")
    (61,"barrier=gate")
    (62,"highway=living_street")
    (63,"bicycle=no")
    (64,"leisure=pitch")
    (65,"tunnel=yes")
    (67,"surface=ground")
    (68,"highway=steps")
    (69,"natural=land")
    (70,"man_made=survey_point")
    (71,"tracktype=grade5")
    (72,"waterway=ditch")
    (73,"leisure=park")
    (74,"amenity=restaurant")
    (75,"barrier=wall")
    (76,"waterway=riverbank")
    (77,"amenity=bench")
    (78,"building=garage")
    (79,"natural=scrub")
    (80,"highway=pedestrian")
    (81,"natural=peak")
    (82,"building=entrance")
    (83,"landuse=reservoir")
    (84,"access=yes")
    (85,"bicycle=designated")
    (86,"leisure=swimming_pool")
    (87,"landuse=farmyard")
    (88,"railway=level_crossing")
    (89,"building=apartments")
    (90,"surface=grass")
    (91,"wheelchair=yes")
    (92,"service=alley")
    (93,"landuse=industrial")
    (94,"amenity=fuel")
    (95,"surface=dirt")
    (96,"highway=trunk_link")
    (97,"waterway=drain")
    (98,"barrier=hedge")
    (99,"amenity=grave_yard")
    (100,"tourism=information")
    (101,"shop=supermarket")
    (102,"highway=primary_link")
    (103,"wood=deciduous")
    (104,"leisure=playground")
    (105,"building=roof")
    (106,"building=industrial")
    (107,"amenity=post_box")
    (108,"waterway=canal")
    (109,"barrier=bollard")
    (110,"leisure=garden")
    (111,"wood=mixed")
    (112,"landuse=cemetery")
    (113,"landuse=orchard")
    (114,"shop=convenience")
    (115,"access=permissive")
    (116,"surface=concrete")
    (117,"surface=paving_stones")
    (118,"service=spur")
    (119,"building=garages")
    (120,"amenity=bank")
    (121,"tourism=hotel")
    (122,"access=no")
    (123,"amenity=fast_food")
    (124,"man_made=pier")
    (125,"amenity=kindergarten")
    (126,"access=agricultural")
    (127,"surface=cobblestone")
    (128,"wheelchair=no")
    (129,"amenity=cafe")
    (130,"amenity=hospital")
    (131,"amenity=post_office")
    (132,"amenity=public_building")
    (133,"amenity=recycling")
    (134,"highway=street_lamp")
    (135,"man_made=tower")
    (136,"waterway=dam")
    (137,"amenity=pub")
    (138,"wood=coniferous")
    (139,"access=destination")
    (140,"admin_level=6")
    (141,"landuse=commercial")
    (142,"amenity=pharmacy")
    (143,"railway=abandoned")
    (144,"service=yard")
    (145,"place=island")
    (146,"oneway=_1")
    (147,"landuse=quarry")
    (149,"landuse=vineyard")
    (150,"highway=motorway_junction")
    (151,"railway=station")
    (152,"landuse=allotments")
    (153,"barrier=lift_gate")
    (154,"admin_level=10")
    (155,"amenity=telephone")
    (156,"place=town")
    (157,"man_made=cutline")
    (158,"place=suburb")
    (159,"aeroway=taxiway")
    (160,"wheelchair=limited")
    (161,"highway=secondary_link")
    (162,"leisure=sports_centre")
    (163,"amenity=bicycle_parking")
    (164,"surface=sand")
    (165,"highway=stop")
    (166,"man_made=works")
    (167,"landuse=retail")
    (168,"amenity=fire_station")
    (169,"service=siding")
    (170,"amenity=toilets")
    (171,"bench=yes")
    (172,"oneway=1")
    (173,"surface=compacted")
    (174,"landuse=basin")
    (175,"amenity=police")
    (176,"railway=tram")
    (177,"route=road")
    (178,"natural=cliff")
    (179,"highway=construction")
    (180,"aeroway=aerodrome")
    ;
/*
    (0,"entrance=yes")
    (0,"man_made=storage_tank")
    (0,"amenity=atm")
    (0,"tourism=attraction")
    (0,"route=bus")
    (0,"shop=bakery")
    (0,"tourism=viewpoint")
    (0,"amenity=swimming_pool")
    (0,"natural=beach")
    (0,"tourism=picnic_site")
    (0,"oneway=true")
    (0,"highway=bridleway")
    (0,"tourism=camp_site")
    (0,"abutters=residential")
    (0,"leisure=nature_reserve")
    (0,"amenity=drinking_water")
    (0,"shop=clothes")
    (0,"natural=heath")
    (0,"highway=mini_roundabout")
    (0,"landuse=construction")
    (0,"amenity=waste_basket")
    (0,"railway=platform")
    (0,"amenity=townhall")
    (0,"shop=hairdresser")
    (0,"amenity=shelter")
    (0,"admin_level=9")
    (0,"building=farm_auxiliary")
    (0,"amenity=library")
    (0,"building=detached")
    (0,"admin_level=4")
    (0,"landuse=village_green")
    (0,"barrier=stile")
    (0,"landuse=garages")
    (0,"amenity=bar")
    (0,"railway=buffer_stop")
    (0,"wetland=marsh")
    (0,"tourism=museum")
    (0,"barrier=cycle_barrier")
    (0,"route=bicycle")
    (0,"railway=tram_stop")
    (0,"amenity=parking_space")
    (0,"barrier=retaining_wall")
    (0,"landuse=recreation_ground")
    (0,"amenity=university")
    (0,"highway=tertiary_link")
    (0,"building=terrace")
    (0,"shop=car_repair")
    (0,"amenity=hunting_stand")
    (0,"amenity=fountain")
    (0,"man_made=pipeline")
    (0,"wetland=swamp")
    (0,"shop=car")
    (0,"bench=no")
    (0,"tunnel=culvert")
    (0,"building=school")
    (0,"barrier=entrance")
    (0,"railway=disused")
    (0,"railway=crossing")
    (0,"building=church")
    (0,"amenity=social_facility")
    (0,"natural=bay")
    (0,"shop=kiosk")
    (0,"amenity=vending_machine")
    (0,"route=hiking")
    (0,"natural=spring")
    (0,"leisure=common")
    (0,"railway=switch")
    (0,"waterway=rapids")
    (0,"admin_level=7")
    (0,"leisure=stadium")
    (0,"leisure=track")
    (0,"place=isolated_dwelling")
    (0,"place=islet")
    (0,"waterway=weir")
    (0,"amenity=doctors")
    (0,"access=designated")
    (0,"landuse=conservation")
    (0,"waterway=artificial")
    (0,"amenity=bus_station")
    (0,"leisure=golf_course")
    (0,"shop=doityourself")
    (0,"building=service")
    (0,"tourism=guest_house")
    (0,"aeroway=runway")
    (0,"place=city")
    (0,"railway=subway")
    (0,"man_made=wastewater_plant")
    (0,"building=commercial")
    (0,"railway=halt")
    (0,"amenity=emergency_phone")
    (0,"building=retail")
    (0,"barrier=block")
    (0,"leisure=recreation_ground")
    (0,"access=forestry")
    (0,"amenity=college")
    (0,"highway=platform")
    (0,"access=unknown")
    (0,"man_made=water_tower")
    (0,"surface=pebblestone")
    (0,"bridge=viaduct")
    (0,"shop=butcher")
    (0,"shop=florist")
    (0,"boundary=landuse")
    (0,"aeroway=helipad")
    (0,"building=hangar")
    (0,"natural=glacier")
    (0,"highway=proposed")
    (0,"shop=mall")
    (0,"barrier=toll_booth")
    (0,"amenity=fire_hydrant")
    (0,"building=manufacture")
    (0,"building=farm")
    (0,"surface=wood")
    (0,"amenity=car_wash")
    (0,"amenity=dentist")
    (0,"natural=marsh")
    (0,"man_made=surveillance")
    (0,"shop=bicycle")
    (0,"route=foot")
    (0,"amenity=theatre")
    (0,"building=office")
    (0,"railway=light_rail")
    (0,"man_made=petroleum_well")
    (0,"amenity=taxi")
    (0,"building=greenhouse")
    (0,"landuse=brownfield")
    (0,"bicycle=permissive")
    (0,"admin_level=2")
    (0,"aeroway=apron")
    (0,"building=cabin")
    (0,"amenity=cinema")
    (0,"access=customers")
    (0,"tourism=motel")
    (0,"railway=narrow_gauge")
    (0,"amenity=marketplace")
    (0,"shop=furniture")
    (0,"entrance=staircase")
    (0,"tourism=artwork")
    (0,"natural=grassland")
    (0,"shop=books")
    (0,"admin_level=5")
    (0,"man_made=groyne")
    (0,"waterway=lock_gate")
    (0,"highway=emergency_access_point")
    (0,"natural=sand")
    (0,"landuse=military")
    (0,"boundary=protected_area")
    (0,"amenity=community_centre")
    (0,"barrier=kissing_gate")
    (0,"highway=speed_camera")
    (0,"boundary=national_park")
    (0,"railway=subway_entrance")
    (0,"man_made=silo")
    (0,"shop=alcohol")
    (0,"highway=give_way")
    (0,"leisure=slipway")
    (0,"shop=electronics")
    (0,"bicycle=dismount")
    (0,"leisure=marina")
    (0,"entrance=main")
    (0,"boundary=postal_code")
    (0,"landuse=greenhouse_horticulture")
    (0,"highway=milestone")
    (0,"natural=cave_entrance")
    (0,"landuse=landfill")
    (0,"shop=chemist")
    (0,"shop=shoes")
    (0,"barrier=cattle_grid")
    (0,"landuse=railway")
    (0,"tourism=hostel")
    (0,"tourism=chalet")
    (0,"place=county")
    (0,"shop=department_store")
    (0,"highway=ford")
    (0,"natural=scree")
    (0,"landuse=greenfield")
    (0,"amenity=nursing_home")
    (0,"barrier=wire_fence")
    (0,"access=restricted")
    (0,"man_made=reservoir_covered")
    (0,"amenity=bicycle_rental")
    (0,"man_made=MDF")
    (0,"man_made=water_well")
    (0,"landuse=field")
    (0,"landuse=wood")
    (0,"shop=hardware")
    (0,"tourism=alpine_hut")
    (0,"natural=tree_row")
    (0,"tourism=caravan_site")
    (0,"bridge=no")
    (0,"wetland=bog")
    (0,"amenity=courthouse")
    (0,"route=ferry")
    (0,"barrier=city_wall")
    (0,"amenity=veterinary")
    (0,"shop=jewelry")
    (0,"building=transportation")
    (0,"amenity=arts_centre")
    (0,"bicycle=official")
    (0,"shop=optician")
    (0,"shop=yes")
    (0,"building=collapsed")
    (0,"shop=garden_centre")
    (0,"man_made=chimney")
    (0,"man_made=mine")
    (0,"bench=unknown")
    (0,"railway=preserved")
    (0,"building=public")
    (0,"amenity=ferry_terminal")
    (0,"highway=raceway")
    (0,"natural=rock")
    (0,"tunnel=no")
    (0,"building=university")
    (0,"shop=beverages")
    (0,"amenity=waste_disposal")
    (0,"building=warehouse")
    (0,"leisure=water_park")
    (0,"shop=gift")
    (0,"place=farm")
    (0,"wetland=tidalflat")
    (0,"waterway=waterfall")
    (0,"man_made=dolphin")
    (0,"service=drive_through")
    (0,"amenity=nightclub")
    (0,"building=shed")
    (0,"shop=greengrocer")
    (0,"natural=fell")
    (0,"wetland=wet_meadow")
    (0,"aeroway=gate")
    (0,"shop=computer")
    (0,"man_made=lighthouse")
    (0,"wetland=reedbed")
    (0,"man_made=breakwater")
    (0,"surface=Dirt_Sand")
    (0,"barrier=ditch")
    (0,"barrier=yes")
    (0,"amenity=biergarten")
    (0,"shop=mobile_phone")
    (0,"route=mtb")
    (0,"amenity=grit_bin")
    (0,"amenity=bbq")
    (0,"shop=sports")
    (0,"barrier=wood_fence")
    (0,"entrance=home")
    (0,"shop=laundry")
    (0,"man_made=gasometer")
    (0,"barrier=embankment")
    (0,"shop=toys")
    (0,"wetland=saltmarsh")
    (0,"waterway=soakhole")
    (0,"shop=travel_agency")
    (0,"man_made=water_works")
    (0,"route=railway")
    (0,"amenity=prison")
    (0,"highway=rest_area")
    (0,"shop=stationery")
    (0,"admin_level=11")
    (0,"building=train_station")
    (0,"building=storage_tank")
    (0,"man_made=windmill")
    (0,"shop=beauty")
    (0,"building=semi")
    (0,"highway=services")
    (0,"bicycle=private")
    (0,"route=ski")
    (0,"service=emergency_access")
    (0,"building=factory")
    (0,"man_made=reinforced_slope")
    (0,"amenity=car_sharing")
    (0,"surface=earth")
    (0,"shop=hifi")
    (0,"amenity=car_rental")
    (0,"barrier=hedge_bank")
    (0,"shop=confectionery")
    (0,"aeroway=terminal")
    (0,"highway=passing_place")
    (0,"building=building")
    (0,"man_made=dyke")
    (0,"building=construction")
    (0,"building=shop")
    (0,"natural=reef")
    (0,"landuse=aquaculture")
    (0,"shop=dry_cleaning")
    (0,"amenity=embassy")
    (0,"shop=newsagent")
    (0,"landuse=salt_pond")
    (0,"railway=spur")
    (0,"wheelchair=unknown")
    (0,"tourism=zoo")
    (0,"man_made=waterway")
    (0,"surface=fine_gravel")
    (0,"shop=motorcycle")
    (0,"building=Building")
    (0,"railway=construction")
    (0,"place=neighbourhood")
    (0,"route=train")
    (0,"building=no")
    (0,"natural=mud")
    (0,"place=region")
    (0,"landuse=reservoir_watershed")
    (0,"boundary=marker")
    (0,"man_made=beacon")
    (0,"shop=outdoor")
    (0,"access=public")
    (0,"abutters=industrial")
    (0,"building=barn")
    (0,"leisure=picnic_table")
    (0,"building=hospital")
    (0,"access=official")
    (0,"shop=variety_store")
    (0,"man_made=crane")
    (0,"amenity=parking_fuel")
    (0,"route=tram")
    (0,"tourism=theme_park")
    (0,"shop=pet")
    (0,"building=kindergarten")
    (0,"man_made=storage")
    (0,"man_made=mast")
    (0,"amenity=parking_entrance")
    (0,"amenity=clock")
    (0,"landuse=industrial_retail")
    (0,"shop=video")
    (0,"access=delivery")
    (0,"amenity=driving_school")
    (0,"service=yes")
    (0,"natural=bare_rock")
    (0,"building=chapel")
    (0,"natural=volcano")
    (0,"waterway=dock")
    (0,"building=dormitory")
    (0,"amenity=boat_storage")
    (0,"man_made=tank")
    (0,"man_made=flagpole")
    (0,"surface=grass_paver")
    (0,"shop=organic")
    (0,"natural=landform")
    (0,"highway=unsurfaced")
    (0,"route=power")
    (0,"surface=mud")
    (0,"building=building_concrete")
    (0,"abutters=retail")
    (0,"building=store")
    (0,"shop=vacant")
    (0,"leisure=miniature_golf")
    (0,"man_made=monitoring_station")
    (0,"natural=waterfall")
    (0,"aeroway=hangar")
    (0,"shop=boutique")
    (0,"route=detour")
    (0,"building=way")
    (0,"railway=stop")
    (0,"amenity=ice_cream")
    (0,"building=storage")
    (0,"shop=car_parts")
    (0,"natural=ridge")
    (0,"shop=tyres")
    (0,"railway=dismantled")
    (0,"amenity=shop")
    (0,"landuse=plant_nursery")
    (0,"building=residentiel1")
    (0,"barrier=field_boundary")
    (0,"barrier=border_control")
    (0,"surface=Paved")
    (0,"barrier=sally_port")
    (0,"amenity=bureau_de_change")
    (0,"leisure=fishing")
    (0,"amenity=charging_station")
    (0,"building=supermarket")
    (0,"highway=stile")
    (0,"amenity=sauna")
    (0,"place=municipality")
    (0,"building=hotel")
    (0,"surface=metal")
    (0,"highway=incline_steep")
    (0,"shop=estate_agent")
    (0,"natural=grass")
    (0,"shop=pharmacy")
    (0,"surface=concrete_plates")
    (0,"shop=copyshop")
    (0,"surface=paving_stones_30")
    (0,"surface=interlock")
    (0,"access=hov")
    (0,"highway=elevator")
    (0,"boundary=local_authority")
    (0,"man_made=communications_tower")
    (0,"shop=deli")
    (0,"barrier=turnstile")
    (0,"building=offices")
    (0,"building=bunker")
    (0,"natural=stone")
    (0,"railway=railway_crossing")
    (0,"leisure=dog_park")
    (0,"building=semi_detached")
    (0,"man_made=watermill")
    (0,"route=trolleybus")
    (0,"admin_level=3")
    (0,"building=block")
    (0,"barrier=guard_rail")
    (0,"bicycle=unknown")
    (0,"highway=abandoned")
    (0,"surface=dirt_sand")
    (0,"barrier=chain")
    (0,"barrier=bump_gate")
    (0,"building=residental")
    (0,"surface=cement")
    (0,"man_made=embankment")
    (0,"building=ruins")
    (0,"highway=incline")
    (0,"abutters=commercial")
    (0,"barrier=hampshire_gate")
    (0,"shop=music")
    (0,"shop=funeral_directors")
    (0,"wetland=mangrove")
    (0,"place=borough")
    (0,"building=apartment")
    (0,"boundary=census")
    (0,"barrier=kerb")
    (0,"building=glasshouse")
    (0,"aeroway=holding_position")
    (0,"shop=general")
    (0,"building=tank")
    (0,"railway=monorail")
    (0,"service=parking")
    (0,"place=state")
    (0,"railway=proposed")
    (0,"shop=art")
    (0,"natural=hill")
    (0,"railway=turntable")
    (0,"tourism=cabin")
    (0,"shop=photo")
    (0,"boundary=lot")
    (0,"shop=fishmonger")
    (0,"amenity=clinic")
    (0,"boundary=political")
    (0,"man_made=well")
    (0,"highway=byway")
    (0,"leisure=horse_riding")
    (0,"service=bus")
    (0,"building=tower")
    (0,"entrance=service")
    (0,"shop=fabric")
    (0,"railway=miniature")
    (0,"abutters=mixed")
    (0,"surface=stone")
    (0,"access=emergency")
    (0,"landuse=mine")
    (0,"amenity=shower")
    (0,"waterway=lock")
    (0,"area=yes")
    ;
*/

boost::optional<tag_type> tag_from_name(name_type const& name)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
    if (right_iter != tag_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    return tag;
}

boost::optional<tag_type> tag_value_from_name(name_type const& name, std::string const& val)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_value_lookup.right.find(name+"="+val);
    if (right_iter != tag_value_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    else
    {
        tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
        if (right_iter != tag_lookup.right.end())
        {
            tag.reset(1024 + right_iter->second);
        }
    }
    return tag;
}


}}
