/*****************************************************************************
 *
 * This file is part of Mapnik (c++ mapping toolkit)
 *
 * Copyright (C) 2012 Artem Pavlenko
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *****************************************************************************/

#include "tags.hpp"

// boost
#include <boost/assign/list_of.hpp>
#include <boost/bimap.hpp>

namespace  mapnik { namespace tags {

typedef boost::bimap<tag_type, name_type> tag_lookup_type;

static const tag_lookup_type tag_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"access")
    (1,"addr:housename")
    (2,"addr:housenumber")
    (3,"addr:interpolation")
    (4,"admin_level")
    (5,"aerialway")
    (6,"aeroway")
    (7 ,"amenity")
    (8 ,"area")
    (9 ,"barrier")
    (10 ,"bicycle")
    (11 ,"brand")
    (12 ,"bridge")
    (13 ,"boundary")
    (14 ,"building")
    (15 ,"construction")
    (16 ,"covered")
    (17 ,"culvert")
    (18 ,"cutting")
    (19 ,"denomination")
    (20 ,"disused")
    (21 ,"embankment")
    (22 ,"foot")
    (23 ,"generator:source")
    (24 ,"harbour")
    (25 ,"highway")
    (26 ,"historic")
    (27 ,"horse")
    (28 ,"intermittent")
    (29 ,"junction")
    (30 ,"landuse")
    (31 ,"layer")
    (32 ,"leisure")
    (33 ,"lock")
    (34 ,"man_made")
    (35 ,"military")
    (36 ,"motorcar")
    (37 ,"name")
    (38 ,"natural")
    (39 ,"oneway")
    (40 ,"operator")
    (41 ,"population")
    (42 ,"power")
    (43 ,"power_source")
    (44 ,"place")
    (45 ,"railway")
    (46 ,"ref")
    (47 ,"religion")
    (48 ,"route")
    (49 ,"service")
    (50 ,"shop")
    (51 ,"sport")
    (52 ,"surface")
    (53 ,"toll")
    (54 ,"tourism")
    (55 ,"tower:type")
    (56 ,"tracktype")
    (57 ,"tunnel")
    (58 ,"water")
    (59 ,"waterway")
    (60 ,"wetland")
    (61 ,"width")
    (62 ,"wood")
    ;

static const tag_lookup_type tag_value_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"building=yes")
    (1,"highway=residential")
    (2,"highway=service")
    (3,"waterway=stream")
    (4,"highway=unclassified")
    (5,"highway=track")
    (6,"oneway=yes")
    (7,"natural=water")
    (8,"highway=footway")
    (9,"access=private")
    (10,"highway=tertiary")
    (11,"highway=path")
    (12,"highway=secondary")
    (13,"landuse=forest")
    (14,"bridge=yes")
    (15,"natural=tree")
    (16,"surface=paved")
    (17,"natural=wood")
    (18,"highway=primary")
    (19,"landuse=grass")
    (20,"landuse=residential")
    (21,"surface=unpaved")
    (22,"highway=bus_stop")
    (23,"surface=asphalt")
    (24,"bicycle=yes")
    (25,"amenity=parking")
    (26,"place=locality")
    (27,"railway=rail")
    (28,"service=parking_aisle")
    (29,"boundary=administrative")
    (30,"building=house")
    (31,"place=village")
    (32,"natural=coastline")
    (33,"tracktype=grade2")
    (34,"oneway=no")
    (35,"service=driveway")
    (36,"highway=turning_circle")
    (37,"place=hamlet")
    (38,"natural=wetland")
    (39,"tracktype=grade3")
    (40,"waterway=river")
    (41,"highway=cycleway")
    (42,"barrier=fence")
    (43,"building=residential")
    (44,"amenity=school")
    (45,"highway=crossing")
    (46,"admin_level=8")
    (47,"highway=trunk")
    (49,"amenity=place_of_worship")
    (50,"landuse=farmland")
    (51,"tracktype=grade1")
    (52,"highway=road")
    (53,"landuse=farm")
    (54,"surface=gravel")
    (55,"landuse=meadow")
    (56,"highway=motorway")
    (57,"highway=traffic_signals")
    (58,"building=hut")
    (59,"highway=motorway_link")
    (60,"tracktype=grade4")
    (61,"barrier=gate")
    (62,"highway=living_street")
    (63,"bicycle=no")
    (64,"leisure=pitch")
    (65,"tunnel=yes")
    (67,"surface=ground")
    (68,"highway=steps")
    (69,"natural=land")
    (70,"man_made=survey_point")
    (71,"tracktype=grade5")
    (72,"waterway=ditch")
    (73,"leisure=park")
    (74,"amenity=restaurant")
    (75,"barrier=wall")
    (76,"waterway=riverbank")
    (77,"amenity=bench")
    (78,"building=garage")
    (79,"natural=scrub")
    (80,"highway=pedestrian")
    (81,"natural=peak")
    (82,"building=entrance")
    (83,"landuse=reservoir")
    (84,"access=yes")
    (85,"bicycle=designated")
    (86,"leisure=swimming_pool")
    (87,"landuse=farmyard")
    (88,"railway=level_crossing")
    (89,"building=apartments")
    (90,"surface=grass")
    (91,"wheelchair=yes")
    (92,"service=alley")
    (93,"landuse=industrial")
    (94,"amenity=fuel")
    (95,"surface=dirt")
    (96,"highway=trunk_link")
    (97,"waterway=drain")
    (98,"barrier=hedge")
    (99,"amenity=grave_yard")
    (100,"tourism=information")
    (101,"shop=supermarket")
    (102,"highway=primary_link")
    (103,"wood=deciduous")
    (104,"leisure=playground")
    (105,"building=roof")
    (106,"building=industrial")
    (107,"amenity=post_box")
    (108,"waterway=canal")
    (109,"barrier=bollard")
    (110,"leisure=garden")
    (111,"wood=mixed")
    (112,"landuse=cemetery")
    (113,"landuse=orchard")
    (114,"shop=convenience")
    (115,"access=permissive")
    (116,"surface=concrete")
    (117,"surface=paving_stones")
    (118,"service=spur")
    (119,"building=garages")
    (120,"amenity=bank")
    (121,"tourism=hotel")
    (122,"access=no")
    (123,"amenity=fast_food")
    (124,"man_made=pier")
    (125,"amenity=kindergarten")
    (126,"access=agricultural")
    (127,"surface=cobblestone")
    (128,"wheelchair=no")
    (129,"amenity=cafe")
    (130,"amenity=hospital")
    (131,"amenity=post_office")
    (132,"amenity=public_building")
    (133,"amenity=recycling")
    (134,"highway=street_lamp")
    (135,"man_made=tower")
    (136,"waterway=dam")
    (137,"amenity=pub")
    (138,"wood=coniferous")
    (139,"access=destination")
    (140,"admin_level=6")
    (141,"landuse=commercial")
    (142,"amenity=pharmacy")
    (143,"railway=abandoned")
    (144,"service=yard")
    (145,"place=island")
    (146,"oneway=_1")
    (147,"landuse=quarry")
    (149,"landuse=vineyard")
    (150,"highway=motorway_junction")
    (151,"railway=station")
    (152,"landuse=allotments")
    (153,"barrier=lift_gate")
    (154,"admin_level=10")
    (155,"amenity=telephone")
    (156,"place=town")
    (157,"man_made=cutline")
    (158,"place=suburb")
    (159,"aeroway=taxiway")
    (160,"wheelchair=limited")
    (161,"highway=secondary_link")
    (162,"leisure=sports_centre")
    (163,"amenity=bicycle_parking")
    (164,"surface=sand")
    (165,"highway=stop")
    (166,"man_made=works")
    (167,"landuse=retail")
    (168,"amenity=fire_station")
    (169,"service=siding")
    (170,"amenity=toilets")
    (171,"bench=yes")
    (172,"oneway=1")
    (173,"surface=compacted")
    (174,"landuse=basin")
    (175,"amenity=police")
    (176,"railway=tram")
    (177,"route=road")
    (178,"natural=cliff")
    (179,"highway=construction")
    (180,"aeroway=aerodrome")
    (181,"entrance=yes")
    (182,"man_made=storage_tank")
    (183,"amenity=atm")
    (184,"tourism=attraction")
    (185,"route=bus")
    (186,"shop=bakery")
    (187,"tourism=viewpoint")
    (188,"amenity=swimming_pool")
    (189,"natural=beach")
    (190,"tourism=picnic_site")
    (191,"oneway=true")
    (192,"highway=bridleway")
    (193,"tourism=camp_site")
    (194,"abutters=residential")
    (195,"leisure=nature_reserve")
    (196,"amenity=drinking_water")
    (197,"shop=clothes")
    (198,"natural=heath")
    (199,"highway=mini_roundabout")
    (200,"landuse=construction")
    (201,"amenity=waste_basket")
    (202,"railway=platform")
    (203,"amenity=townhall")
    (204,"shop=hairdresser")
    (205,"amenity=shelter")
    (206,"admin_level=9")
    (207,"building=farm_auxiliary")
    (208,"amenity=library")
    (209,"building=detached")
    (210,"admin_level=4")
    (211,"landuse=village_green")
    (212,"barrier=stile")
    (213,"landuse=garages")
    (214,"amenity=bar")
    (215,"railway=buffer_stop")
    (216,"wetland=marsh")
    (217,"tourism=museum")
    (218,"barrier=cycle_barrier")
    (219,"route=bicycle")
    (220,"railway=tram_stop")
    (221,"amenity=parking_space")
    (222,"barrier=retaining_wall")
    (223,"landuse=recreation_ground")
    (224,"amenity=university")
    (225,"highway=tertiary_link")
    (226,"building=terrace")
    (227,"shop=car_repair")
    (228,"amenity=hunting_stand")
    (229,"amenity=fountain")
    (230,"man_made=pipeline")
    (231,"wetland=swamp")
    (232,"shop=car")
    (233,"bench=no")
    (234,"tunnel=culvert")
    (235,"building=school")
    (236,"barrier=entrance")
    (237,"railway=disused")
    (238,"railway=crossing")
    (239,"building=church")
    (240,"amenity=social_facility")
    (241,"natural=bay")
    (242,"shop=kiosk")
    (243,"amenity=vending_machine")
    (244,"route=hiking")
    (245,"natural=spring")
    (246,"leisure=common")
    (247,"railway=switch")
    (248,"waterway=rapids")
    (249,"admin_level=7")
    (250,"leisure=stadium")
    (251,"leisure=track")
    (252,"place=isolated_dwelling")
    (253,"place=islet")
    (254,"waterway=weir")
    (255,"amenity=doctors")
    (256,"access=designated")
    (257,"landuse=conservation")
    (258,"waterway=artificial")
    (259,"amenity=bus_station")
    (260,"leisure=golf_course")
    (261,"shop=doityourself")
    (262,"building=service")
    (263,"tourism=guest_house")
    (264,"aeroway=runway")
    (265,"place=city")
    (266,"railway=subway")
    (267,"man_made=wastewater_plant")
    (268,"building=commercial")
    (269,"railway=halt")
    (270,"amenity=emergency_phone")
    (271,"building=retail")
    (272,"barrier=block")
    (273,"leisure=recreation_ground")
    (274,"access=forestry")
    (275,"amenity=college")
    (276,"highway=platform")
    (277,"access=unknown")
    (278,"man_made=water_tower")
    (279,"surface=pebblestone")
    (280,"bridge=viaduct")
    (281,"shop=butcher")
    (282,"shop=florist")
    (283,"boundary=landuse")
    (284,"aeroway=helipad")
    (285,"building=hangar")
    (286,"natural=glacier")
    (287,"highway=proposed")
    (288,"shop=mall")
    (289,"barrier=toll_booth")
    (290,"amenity=fire_hydrant")
    (291,"building=manufacture")
    (292,"building=farm")
    (293,"surface=wood")
    (294,"amenity=car_wash")
    (295,"amenity=dentist")
    (296,"natural=marsh")
    (297,"man_made=surveillance")
    (298,"shop=bicycle")
    (299,"route=foot")
    (300,"amenity=theatre")
    (300,"building=office")
    (301,"railway=light_rail")
    (302,"man_made=petroleum_well")
    (303,"amenity=taxi")
    (304,"building=greenhouse")
    (305,"landuse=brownfield")
    (306,"bicycle=permissive")
    (307,"admin_level=2")
    (308,"aeroway=apron")
    (309,"building=cabin")
    (310,"amenity=cinema")
    (311,"access=customers")
    (312,"tourism=motel")
    (313,"railway=narrow_gauge")
    (314,"amenity=marketplace")
    (315,"shop=furniture")
    (316,"entrance=staircase")
    (317,"tourism=artwork")
    (318,"natural=grassland")
    (319,"shop=books")
    (320,"admin_level=5")
    (321,"man_made=groyne")
    (322,"waterway=lock_gate")
    (323,"highway=emergency_access_point")
    (324,"natural=sand")
    (325,"landuse=military")
    (326,"boundary=protected_area")
    (327,"amenity=community_centre")
    (328,"barrier=kissing_gate")
    (329,"highway=speed_camera")
    (330,"boundary=national_park")
    (331,"railway=subway_entrance")
    (332,"man_made=silo")
    (333,"shop=alcohol")
    (334,"highway=give_way")
    (335,"leisure=slipway")
    (336,"shop=electronics")
    (337,"bicycle=dismount")
    (338,"leisure=marina")
    (339,"entrance=main")
    (340,"boundary=postal_code")
    (341,"landuse=greenhouse_horticulture")
    (342,"highway=milestone")
    (343,"natural=cave_entrance")
    (344,"landuse=landfill")
    (345,"shop=chemist")
    (346,"shop=shoes")
    (347,"barrier=cattle_grid")
    (348,"landuse=railway")
    (349,"tourism=hostel")
    (350,"tourism=chalet")
    (351,"place=county")
    (352,"shop=department_store")
    (353,"highway=ford")
    (354,"natural=scree")
    (355,"landuse=greenfield")
    (356,"amenity=nursing_home")
    (357,"barrier=wire_fence")
    (358,"access=restricted")
    (359,"man_made=reservoir_covered")
    (360,"amenity=bicycle_rental")
    (361,"man_made=MDF")
    (362,"man_made=water_well")
    (363,"landuse=field")
    (364,"landuse=wood")
    (365,"shop=hardware")
    (366,"tourism=alpine_hut")
    (367,"natural=tree_row")
    (368,"tourism=caravan_site")
    (369,"bridge=no")
    (370,"wetland=bog")
    (371,"amenity=courthouse")
    (372,"route=ferry")
    (373,"barrier=city_wall")
    (374,"amenity=veterinary")
    (375,"shop=jewelry")
    (376,"building=transportation")
    (377,"amenity=arts_centre")
    (378,"bicycle=official")
    (379,"shop=optician")
    (380,"shop=yes")
    (381,"building=collapsed")
    (382,"shop=garden_centre")
    (383,"man_made=chimney")
    (384,"man_made=mine")
    (385,"bench=unknown")
    (386,"railway=preserved")
    (387,"building=public")
    (388,"amenity=ferry_terminal")
    (389,"highway=raceway")
    (390,"natural=rock")
    (391,"tunnel=no")
    (392,"building=university")
    (393,"shop=beverages")
    (394,"amenity=waste_disposal")
    (395,"building=warehouse")
    (396,"leisure=water_park")
    (397,"shop=gift")
    (398,"place=farm")
    (399,"wetland=tidalflat")
    (400,"waterway=waterfall")
    (401,"man_made=dolphin")
    (402,"service=drive_through")
    (403,"amenity=nightclub")
    (404,"building=shed")
    (405,"shop=greengrocer")
    (406,"natural=fell")
    (407,"wetland=wet_meadow")
    (408,"aeroway=gate")
    (409,"shop=computer")
    (410,"man_made=lighthouse")
    (411,"wetland=reedbed")
    (412,"man_made=breakwater")
    (413,"surface=Dirt_Sand")
    (414,"barrier=ditch")
    (415,"barrier=yes")
    (416,"amenity=biergarten")
    (417,"shop=mobile_phone")
    (418,"route=mtb")
    (419,"amenity=grit_bin")
    (420,"amenity=bbq")
    (421,"shop=sports")
    (422,"barrier=wood_fence")
    (423,"entrance=home")
    (424,"shop=laundry")
    (425,"man_made=gasometer")
    (426,"barrier=embankment")
    (427,"shop=toys")
    (428,"wetland=saltmarsh")
    (429,"waterway=soakhole")
    (430,"shop=travel_agency")
    (431,"man_made=water_works")
    (432,"route=railway")
    (433,"amenity=prison")
    (434,"highway=rest_area")
    (435,"shop=stationery")
    (436,"admin_level=11")
    (437,"building=train_station")
    (438,"building=storage_tank")
    (439,"man_made=windmill")
    (440,"shop=beauty")
    (441,"building=semi")
    (442,"highway=services")
    (443,"bicycle=private")
    (444,"route=ski")
    (445,"service=emergency_access")
    (446,"building=factory")
    (447,"man_made=reinforced_slope")
    (448,"amenity=car_sharing")
    (449,"surface=earth")
    (450,"shop=hifi")
    ;
/*
    (0,"amenity=car_rental")
    (0,"barrier=hedge_bank")
    (0,"shop=confectionery")
    (0,"aeroway=terminal")
    (0,"highway=passing_place")
    (0,"building=building")
    (0,"man_made=dyke")
    (0,"building=construction")
    (0,"building=shop")
    (0,"natural=reef")
    (0,"landuse=aquaculture")
    (0,"shop=dry_cleaning")
    (0,"amenity=embassy")
    (0,"shop=newsagent")
    (0,"landuse=salt_pond")
    (0,"railway=spur")
    (0,"wheelchair=unknown")
    (0,"tourism=zoo")
    (0,"man_made=waterway")
    (0,"surface=fine_gravel")
    (0,"shop=motorcycle")
    (0,"building=Building")
    (0,"railway=construction")
    (0,"place=neighbourhood")
    (0,"route=train")
    (0,"building=no")
    (0,"natural=mud")
    (0,"place=region")
    (0,"landuse=reservoir_watershed")
    (0,"boundary=marker")
    (0,"man_made=beacon")
    (0,"shop=outdoor")
    (0,"access=public")
    (0,"abutters=industrial")
    (0,"building=barn")
    (0,"leisure=picnic_table")
    (0,"building=hospital")
    (0,"access=official")
    (0,"shop=variety_store")
    (0,"man_made=crane")
    (0,"amenity=parking_fuel")
    (0,"route=tram")
    (0,"tourism=theme_park")
    (0,"shop=pet")
    (0,"building=kindergarten")
    (0,"man_made=storage")
    (0,"man_made=mast")
    (0,"amenity=parking_entrance")
    (0,"amenity=clock")
    (0,"landuse=industrial_retail")
    (0,"shop=video")
    (0,"access=delivery")
    (0,"amenity=driving_school")
    (0,"service=yes")
    (0,"natural=bare_rock")
    (0,"building=chapel")
    (0,"natural=volcano")
    (0,"waterway=dock")
    (0,"building=dormitory")
    (0,"amenity=boat_storage")
    (0,"man_made=tank")
    (0,"man_made=flagpole")
    (0,"surface=grass_paver")
    (0,"shop=organic")
    (0,"natural=landform")
    (0,"highway=unsurfaced")
    (0,"route=power")
    (0,"surface=mud")
    (0,"building=building_concrete")
    (0,"abutters=retail")
    (0,"building=store")
    (0,"shop=vacant")
    (0,"leisure=miniature_golf")
    (0,"man_made=monitoring_station")
    (0,"natural=waterfall")
    (0,"aeroway=hangar")
    (0,"shop=boutique")
    (0,"route=detour")
    (0,"building=way")
    (0,"railway=stop")
    (0,"amenity=ice_cream")
    (0,"building=storage")
    (0,"shop=car_parts")
    (0,"natural=ridge")
    (0,"shop=tyres")
    (0,"railway=dismantled")
    (0,"amenity=shop")
    (0,"landuse=plant_nursery")
    (0,"building=residentiel1")
    (0,"barrier=field_boundary")
    (0,"barrier=border_control")
    (0,"surface=Paved")
    (0,"barrier=sally_port")
    (0,"amenity=bureau_de_change")
    (0,"leisure=fishing")
    (0,"amenity=charging_station")
    (0,"building=supermarket")
    (0,"highway=stile")
    (0,"amenity=sauna")
    (0,"place=municipality")
    (0,"building=hotel")
    (0,"surface=metal")
    (0,"highway=incline_steep")
    (0,"shop=estate_agent")
    (0,"natural=grass")
    (0,"shop=pharmacy")
    (0,"surface=concrete_plates")
    (0,"shop=copyshop")
    (0,"surface=paving_stones_30")
    (0,"surface=interlock")
    (0,"access=hov")
    (0,"highway=elevator")
    (0,"boundary=local_authority")
    (0,"man_made=communications_tower")
    (0,"shop=deli")
    (0,"barrier=turnstile")
    (0,"building=offices")
    (0,"building=bunker")
    (0,"natural=stone")
    (0,"railway=railway_crossing")
    (0,"leisure=dog_park")
    (0,"building=semi_detached")
    (0,"man_made=watermill")
    (0,"route=trolleybus")
    (0,"admin_level=3")
    (0,"building=block")
    (0,"barrier=guard_rail")
    (0,"bicycle=unknown")
    (0,"highway=abandoned")
    (0,"surface=dirt_sand")
    (0,"barrier=chain")
    (0,"barrier=bump_gate")
    (0,"building=residental")
    (0,"surface=cement")
    (0,"man_made=embankment")
    (0,"building=ruins")
    (0,"highway=incline")
    (0,"abutters=commercial")
    (0,"barrier=hampshire_gate")
    (0,"shop=music")
    (0,"shop=funeral_directors")
    (0,"wetland=mangrove")
    (0,"place=borough")
    (0,"building=apartment")
    (0,"boundary=census")
    (0,"barrier=kerb")
    (0,"building=glasshouse")
    (0,"aeroway=holding_position")
    (0,"shop=general")
    (0,"building=tank")
    (0,"railway=monorail")
    (0,"service=parking")
    (0,"place=state")
    (0,"railway=proposed")
    (0,"shop=art")
    (0,"natural=hill")
    (0,"railway=turntable")
    (0,"tourism=cabin")
    (0,"shop=photo")
    (0,"boundary=lot")
    (0,"shop=fishmonger")
    (0,"amenity=clinic")
    (0,"boundary=political")
    (0,"man_made=well")
    (0,"highway=byway")
    (0,"leisure=horse_riding")
    (0,"service=bus")
    (0,"building=tower")
    (0,"entrance=service")
    (0,"shop=fabric")
    (0,"railway=miniature")
    (0,"abutters=mixed")
    (0,"surface=stone")
    (0,"access=emergency")
    (0,"landuse=mine")
    (0,"amenity=shower")
    (0,"waterway=lock")
    (0,"area=yes")
    ;
*/

boost::optional<tag_type> tag_from_name(name_type const& name)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
    if (right_iter != tag_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    return tag;
}

boost::optional<tag_type> tag_value_from_name(name_type const& name, std::string const& val)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_value_lookup.right.find(name+"="+val);
    if (right_iter != tag_value_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    else
    {
        tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
        if (right_iter != tag_lookup.right.end())
        {
            tag.reset(1024 + right_iter->second);
        }
    }
    return tag;
}


}}
