/*****************************************************************************
 *
 * This file is part of Mapnik (c++ mapping toolkit)
 *
 * Copyright (C) 2012 Artem Pavlenko
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *****************************************************************************/

#include "tags.hpp"

// boost
#include <boost/assign/list_of.hpp>
#include <boost/bimap.hpp>

namespace  mapnik { namespace tags {

typedef boost::bimap<tag_type, name_type> tag_lookup_type;

static const tag_lookup_type tag_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"access")
    (1,"addr:housename")
    (2,"addr:housenumber")
    (3,"addr:interpolation")
    (4,"admin_level")
    (5,"aerialway")
    (6,"aeroway")
    (7 ,"amenity")
    (8 ,"area")
    (9 ,"barrier")
    (10 ,"bicycle")
    (11 ,"brand")
    (12 ,"bridge")
    (13 ,"boundary")
    (14 ,"building")
    (15 ,"construction")
    (16 ,"covered")
    (17 ,"culvert")
    (18 ,"cutting")
    (19 ,"denomination")
    (20 ,"disused")
    (21 ,"embankment")
    (22 ,"foot")
    (23 ,"generator:source")
    (24 ,"harbour")
    (25 ,"highway")
    (26 ,"historic")
    (27 ,"horse")
    (28 ,"intermittent")
    (29 ,"junction")
    (30 ,"landuse")
    (31 ,"layer")
    (32 ,"leisure")
    (33 ,"lock")
    (34 ,"man_made")
    (35 ,"military")
    (36 ,"motorcar")
    (37 ,"name")
    (38 ,"natural")
    (39 ,"oneway")
    (40 ,"operator")
    (41 ,"population")
    (42 ,"power")
    (43 ,"power_source")
    (44 ,"place")
    (45 ,"railway")
    (46 ,"ref")
    (47 ,"religion")
    (48 ,"route")
    (49 ,"service")
    (50 ,"shop")
    (51 ,"sport")
    (52 ,"surface")
    (53 ,"toll")
    (54 ,"tourism")
    (55 ,"tower:type")
    (56 ,"tracktype")
    (57 ,"tunnel")
    (58 ,"water")
    (59 ,"waterway")
    (60 ,"wetland")
    (61 ,"width")
    (62 ,"wood")
    ;

static const tag_lookup_type tag_value_lookup = boost::assign::list_of<tag_lookup_type::relation>
    (0,"building=yes")
    (1,"highway=residential")
    (2,"highway=service")
    (3,"waterway=stream")
    (4,"highway=unclassified")
    (5,"highway=track")
    (6,"oneway=yes")
    (7,"natural=water")
    (8,"highway=footway")
    (9,"access=private")
    (10,"highway=tertiary")
    (11,"highway=path")
    (12,"highway=secondary")
    (13,"landuse=forest")
    (14,"bridge=yes")
    (15,"natural=tree")
    (16,"surface=paved")
    (17,"natural=wood")
    (18,"highway=primary")
    (19,"landuse=grass")
    (20,"landuse=residential")
    (21,"surface=unpaved")
    (22,"highway=bus_stop")
    (23,"surface=asphalt")
    (24,"bicycle=yes")
    (25,"amenity=parking")
    (26,"place=locality")
    (27,"railway=rail")
    (28,"service=parking_aisle")
    (29,"boundary=administrative")
    (30,"building=house")
    (31,"place=village")
    (32,"natural=coastline")
    (33,"tracktype=grade2")
    (34,"oneway=no")
    (35,"service=driveway")
    (36,"highway=turning_circle")
    (37,"place=hamlet")
    (38,"natural=wetland")
    (39,"tracktype=grade3")
    (40,"waterway=river")
    (41,"highway=cycleway")
    (42,"barrier=fence")
    (43,"building=residential")
    (44,"amenity=school")
    (45,"highway=crossing")
    (46,"admin_level=8")
    (47,"highway=trunk")
    (48,"amenity=place_of_worship")
    (49,"landuse=farmland")
    (50,"tracktype=grade1")
    (51,"highway=road")
    (52,"landuse=farm")
    (53,"surface=gravel")
    (54,"landuse=meadow")
    (55,"highway=motorway")
    (56,"highway=traffic_signals")
    (57,"building=hut")
    (58,"highway=motorway_link")
    (59,"tracktype=grade4")
    (60,"barrier=gate")
    (61,"highway=living_street")
    (62,"bicycle=no")
    (63,"leisure=pitch")
    (64,"tunnel=yes")
    (65,"surface=ground")
    (66,"highway=steps")
    (67,"natural=land")
    (68,"man_made=survey_point")
    (69,"tracktype=grade5")
    (70,"waterway=ditch")
    (71,"leisure=park")
    (72,"amenity=restaurant")
    (73,"barrier=wall")
    (74,"waterway=riverbank")
    (75,"amenity=bench")
    (76,"building=garage")
    (77,"natural=scrub")
    (78,"highway=pedestrian")
    (79,"natural=peak")
    (80,"building=entrance")
    (81,"landuse=reservoir")
    (82,"access=yes")
    (83,"bicycle=designated")
    (84,"leisure=swimming_pool")
    (85,"landuse=farmyard")
    (86,"railway=level_crossing")
    (87,"building=apartments")
    (88,"surface=grass")
    (89,"wheelchair=yes")
    (90,"service=alley")
    (91,"landuse=industrial")
    (92,"amenity=fuel")
    (93,"surface=dirt")
    (94,"highway=trunk_link")
    (95,"waterway=drain")
    (96,"barrier=hedge")
    (97,"amenity=grave_yard")
    (98,"tourism=information")
    (99,"shop=supermarket")
    (100,"highway=primary_link")
    (101,"wood=deciduous")
    (102,"leisure=playground")
    (103,"building=roof")
    (104,"building=industrial")
    (105,"amenity=post_box")
    (106,"waterway=canal")
    (107,"barrier=bollard")
    (108,"leisure=garden")
    (109,"wood=mixed")
    (110,"landuse=cemetery")
    (111,"landuse=orchard")
    (112,"shop=convenience")
    (113,"access=permissive")
    (114,"surface=concrete")
    (115,"surface=paving_stones")
    (116,"service=spur")
    (117,"building=garages")
    (118,"amenity=bank")
    (119,"tourism=hotel")
    (120,"access=no")
    (121,"amenity=fast_food")
    (122,"man_made=pier")
    (123,"amenity=kindergarten")
    (124,"access=agricultural")
    (125,"surface=cobblestone")
    (126,"wheelchair=no")
    (127,"amenity=cafe")
    (128,"amenity=hospital")
    (129,"amenity=post_office")
    (130,"amenity=public_building")
    (131,"amenity=recycling")
    (132,"highway=street_lamp")
    (133,"man_made=tower")
    (134,"waterway=dam")
    (135,"amenity=pub")
    (136,"wood=coniferous")
    (137,"access=destination")
    (138,"admin_level=6")
    (139,"landuse=commercial")
    (140,"amenity=pharmacy")
    (141,"railway=abandoned")
    (142,"service=yard")
    (143,"place=island")
    (144,"oneway=_1")
    (145,"landuse=quarry")
    (146,"landuse=vineyard")
    (147,"highway=motorway_junction")
    (148,"railway=station")
    (149,"landuse=allotments")
    (150,"barrier=lift_gate")
    (151,"admin_level=10")
    (152,"amenity=telephone")
    (153,"place=town")
    (154,"man_made=cutline")
    (155,"place=suburb")
    (156,"aeroway=taxiway")
    (157,"wheelchair=limited")
    (158,"highway=secondary_link")
    (159,"leisure=sports_centre")
    (160,"amenity=bicycle_parking")
    (161,"surface=sand")
    (162,"highway=stop")
    (163,"man_made=works")
    (164,"landuse=retail")
    (165,"amenity=fire_station")
    (166,"service=siding")
    (167,"amenity=toilets")
    (168,"bench=yes")
    (169,"oneway=1")
    (170,"surface=compacted")
    (171,"landuse=basin")
    (172,"amenity=police")
    (173,"railway=tram")
    (174,"route=road")
    (175,"natural=cliff")
    (176,"highway=construction")
    (177,"aeroway=aerodrome")
    (178,"entrance=yes")
    (179,"man_made=storage_tank")
    (180,"amenity=atm")
    (181,"tourism=attraction")
    (182,"route=bus")
    (183,"shop=bakery")
    (184,"tourism=viewpoint")
    (185,"amenity=swimming_pool")
    (186,"natural=beach")
    (187,"tourism=picnic_site")
    (188,"oneway=true")
    (189,"highway=bridleway")
    (190,"tourism=camp_site")
    (191,"abutters=residential")
    (192,"leisure=nature_reserve")
    (193,"amenity=drinking_water")
    (194,"shop=clothes")
    (195,"natural=heath")
    (196,"highway=mini_roundabout")
    (197,"landuse=construction")
    (198,"amenity=waste_basket")
    (199,"railway=platform")
    (200,"amenity=townhall")
    (201,"shop=hairdresser")
    (202,"amenity=shelter")
    (203,"admin_level=9")
    (204,"building=farm_auxiliary")
    (205,"amenity=library")
    (206,"building=detached")
    (207,"admin_level=4")
    (208,"landuse=village_green")
    (209,"barrier=stile")
    (210,"landuse=garages")
    (211,"amenity=bar")
    (212,"railway=buffer_stop")
    (213,"wetland=marsh")
    (214,"tourism=museum")
    (215,"barrier=cycle_barrier")
    (216,"route=bicycle")
    (217,"railway=tram_stop")
    (218,"amenity=parking_space")
    (219,"barrier=retaining_wall")
    (220,"landuse=recreation_ground")
    (221,"amenity=university")
    (222,"highway=tertiary_link")
    (223,"building=terrace")
    (224,"shop=car_repair")
    (225,"amenity=hunting_stand")
    (226,"amenity=fountain")
    (227,"man_made=pipeline")
    (228,"wetland=swamp")
    (229,"shop=car")
    (230,"bench=no")
    (231,"tunnel=culvert")
    (232,"building=school")
    (233,"barrier=entrance")
    (234,"railway=disused")
    (235,"railway=crossing")
    (236,"building=church")
    (237,"amenity=social_facility")
    (238,"natural=bay")
    (239,"shop=kiosk")
    (240,"amenity=vending_machine")
    (241,"route=hiking")
    (242,"natural=spring")
    (243,"leisure=common")
    (244,"railway=switch")
    (245,"waterway=rapids")
    (246,"admin_level=7")
    (247,"leisure=stadium")
    (248,"leisure=track")
    (249,"place=isolated_dwelling")
    (250,"place=islet")
    (251,"waterway=weir")
    (252,"amenity=doctors")
    (253,"access=designated")
    (254,"landuse=conservation")
    (255,"waterway=artificial")
    (256,"amenity=bus_station")
    (257,"leisure=golf_course")
    (258,"shop=doityourself")
    (259,"building=service")
    (260,"tourism=guest_house")
    (261,"aeroway=runway")
    (262,"place=city")
    (263,"railway=subway")
    (264,"man_made=wastewater_plant")
    (265,"building=commercial")
    (266,"railway=halt")
    (267,"amenity=emergency_phone")
    (268,"building=retail")
    (269,"barrier=block")
    (270,"leisure=recreation_ground")
    (271,"access=forestry")
    (272,"amenity=college")
    (273,"highway=platform")
    (274,"access=unknown")
    (275,"man_made=water_tower")
    (276,"surface=pebblestone")
    (277,"bridge=viaduct")
    (278,"shop=butcher")
    (279,"shop=florist")
    (280,"boundary=landuse")
    (281,"aeroway=helipad")
    (282,"building=hangar")
    (283,"natural=glacier")
    (284,"highway=proposed")
    (285,"shop=mall")
    (286,"barrier=toll_booth")
    (287,"amenity=fire_hydrant")
    (288,"building=manufacture")
    (289,"building=farm")
    (290,"surface=wood")
    (291,"amenity=car_wash")
    (292,"amenity=dentist")
    (293,"natural=marsh")
    (294,"man_made=surveillance")
    (295,"shop=bicycle")
    (296,"route=foot")
    (297,"amenity=theatre")
    (298,"building=office")
    (299,"railway=light_rail")
    (300,"man_made=petroleum_well")
    (301,"amenity=taxi")
    (302,"building=greenhouse")
    (303,"landuse=brownfield")
    (304,"bicycle=permissive")
    (305,"admin_level=2")
    (306,"aeroway=apron")
    (307,"building=cabin")
    (308,"amenity=cinema")
    (309,"access=customers")
    (310,"tourism=motel")
    (311,"railway=narrow_gauge")
    (312,"amenity=marketplace")
    (313,"shop=furniture")
    (314,"entrance=staircase")
    (315,"tourism=artwork")
    (316,"natural=grassland")
    (317,"shop=books")
    (318,"admin_level=5")
    (319,"man_made=groyne")
    (320,"waterway=lock_gate")
    (321,"highway=emergency_access_point")
    (322,"natural=sand")
    (323,"landuse=military")
    (324,"boundary=protected_area")
    (325,"amenity=community_centre")
    (326,"barrier=kissing_gate")
    (327,"highway=speed_camera")
    (328,"boundary=national_park")
    (329,"railway=subway_entrance")
    (330,"man_made=silo")
    (331,"shop=alcohol")
    (332,"highway=give_way")
    (333,"leisure=slipway")
    (334,"shop=electronics")
    (335,"bicycle=dismount")
    (336,"leisure=marina")
    (337,"entrance=main")
    (338,"boundary=postal_code")
    (339,"landuse=greenhouse_horticulture")
    (340,"highway=milestone")
    (341,"natural=cave_entrance")
    (342,"landuse=landfill")
    (343,"shop=chemist")
    (344,"shop=shoes")
    (345,"barrier=cattle_grid")
    (346,"landuse=railway")
    (347,"tourism=hostel")
    (348,"tourism=chalet")
    (349,"place=county")
    (350,"shop=department_store")
    (351,"highway=ford")
    (352,"natural=scree")
    (353,"landuse=greenfield")
    (354,"amenity=nursing_home")
    (355,"barrier=wire_fence")
    (356,"access=restricted")
    (357,"man_made=reservoir_covered")
    (358,"amenity=bicycle_rental")
    (359,"man_made=MDF")
    (360,"man_made=water_well")
    (361,"landuse=field")
    (362,"landuse=wood")
    (363,"shop=hardware")
    (364,"tourism=alpine_hut")
    (365,"natural=tree_row")
    (366,"tourism=caravan_site")
    (367,"bridge=no")
    (368,"wetland=bog")
    (369,"amenity=courthouse")
    (370,"route=ferry")
    (371,"barrier=city_wall")
    (372,"amenity=veterinary")
    (373,"shop=jewelry")
    (374,"building=transportation")
    (375,"amenity=arts_centre")
    (376,"bicycle=official")
    (377,"shop=optician")
    (378,"shop=yes")
    (379,"building=collapsed")
    (380,"shop=garden_centre")
    (381,"man_made=chimney")
    (382,"man_made=mine")
    (383,"bench=unknown")
    (384,"railway=preserved")
    (385,"building=public")
    (386,"amenity=ferry_terminal")
    (387,"highway=raceway")
    (388,"natural=rock")
    (389,"tunnel=no")
    (390,"building=university")
    (391,"shop=beverages")
    (392,"amenity=waste_disposal")
    (393,"building=warehouse")
    (394,"leisure=water_park")
    (395,"shop=gift")
    (396,"place=farm")
    (397,"wetland=tidalflat")
    (398,"waterway=waterfall")
    (399,"man_made=dolphin")
    (400,"service=drive_through")
    (401,"amenity=nightclub")
    (402,"building=shed")
    (403,"shop=greengrocer")
    (404,"natural=fell")
    (405,"wetland=wet_meadow")
    (406,"aeroway=gate")
    (407,"shop=computer")
    (408,"man_made=lighthouse")
    (409,"wetland=reedbed")
    (410,"man_made=breakwater")
    (411,"surface=Dirt_Sand")
    (412,"barrier=ditch")
    (413,"barrier=yes")
    (414,"amenity=biergarten")
    (415,"shop=mobile_phone")
    (416,"route=mtb")
    (417,"amenity=grit_bin")
    (418,"amenity=bbq")
    (419,"shop=sports")
    (420,"barrier=wood_fence")
    (421,"entrance=home")
    (422,"shop=laundry")
    (423,"man_made=gasometer")
    (424,"barrier=embankment")
    (425,"shop=toys")
    (426,"wetland=saltmarsh")
    (427,"waterway=soakhole")
    (428,"shop=travel_agency")
    (429,"man_made=water_works")
    (430,"route=railway")
    (431,"amenity=prison")
    (432,"highway=rest_area")
    (433,"shop=stationery")
    (434,"admin_level=11")
    (435,"building=train_station")
    (436,"building=storage_tank")
    (437,"man_made=windmill")
    (438,"shop=beauty")
    (439,"building=semi")
    (440,"highway=services")
    (441,"bicycle=private")
    (442,"route=ski")
    (443,"service=emergency_access")
    (444,"building=factory")
    (445,"man_made=reinforced_slope")
    (446,"amenity=car_sharing")
    (447,"surface=earth")
    (448,"shop=hifi")
    (449,"amenity=car_rental")
    (450,"barrier=hedge_bank")
    (451,"shop=confectionery")
    (452,"aeroway=terminal")
    (453,"highway=passing_place")
    (454,"building=building")
    (455,"man_made=dyke")
    (456,"building=construction")
    (457,"building=shop")
    (458,"natural=reef")
    (459,"landuse=aquaculture")
    (460,"shop=dry_cleaning")
    (461,"amenity=embassy")
    (462,"shop=newsagent")
    (463,"landuse=salt_pond")
    (464,"railway=spur")
    (465,"wheelchair=unknown")
    (466,"tourism=zoo")
    (467,"man_made=waterway")
    (468,"surface=fine_gravel")
    (469,"shop=motorcycle")
    (470,"building=Building")
    (471,"railway=construction")
    (472,"place=neighbourhood")
    (473,"route=train")
    (474,"building=no")
    (475,"natural=mud")
    (476,"place=region")
    (477,"landuse=reservoir_watershed")
    (478,"boundary=marker")
    (479,"man_made=beacon")
    (480,"shop=outdoor")
    (481,"access=public")
    (482,"abutters=industrial")
    (483,"building=barn")
    (484,"leisure=picnic_table")
    (485,"building=hospital")
    (486,"access=official")
    (487,"shop=variety_store")
    (488,"man_made=crane")
    (489,"amenity=parking_fuel")
    (490,"route=tram")
    (491,"tourism=theme_park")
    (492,"shop=pet")
    (493,"building=kindergarten")
    (494,"man_made=storage")
    (495,"man_made=mast")
    (496,"amenity=parking_entrance")
    (497,"amenity=clock")
    (498,"landuse=industrial_retail")
    (499,"shop=video")
    (500,"access=delivery")
    (501,"amenity=driving_school")
    (502,"service=yes")
    (503,"natural=bare_rock")
    (504,"building=chapel")
    (505,"natural=volcano")
    (506,"waterway=dock")
    (507,"building=dormitory")
    (508,"amenity=boat_storage")
    (509,"man_made=tank")
    (510,"man_made=flagpole")
    (511,"surface=grass_paver")
    (512,"shop=organic")
    (513,"natural=landform")
    (514,"highway=unsurfaced")
    (515,"route=power")
    (516,"surface=mud")
    (517,"building=building_concrete")
    (518,"abutters=retail")
    (519,"building=store")
    (520,"shop=vacant")
    (521,"leisure=miniature_golf")
    (522,"man_made=monitoring_station")
    (523,"natural=waterfall")
    (524,"aeroway=hangar")
    (525,"shop=boutique")
    (526,"route=detour")
    (527,"building=way")
    (528,"railway=stop")
    (529,"amenity=ice_cream")
    (530,"building=storage")
    (531,"shop=car_parts")
    (532,"natural=ridge")
    (533,"shop=tyres")
    (534,"railway=dismantled")
    (535,"amenity=shop")
    (536,"landuse=plant_nursery")
    (537,"building=residentiel1")
    (538,"barrier=field_boundary")
    (539,"barrier=border_control")
    (540,"surface=Paved")
    (541,"barrier=sally_port")
    (542,"amenity=bureau_de_change")
    (543,"leisure=fishing")
    (544,"amenity=charging_station")
    (545,"building=supermarket")
    (546,"highway=stile")
    (547,"amenity=sauna")
    (548,"place=municipality")
    (549,"building=hotel")
    (550,"surface=metal")
    (551,"highway=incline_steep")
    (552,"shop=estate_agent")
    (553,"natural=grass")
    (554,"shop=pharmacy")
    (555,"surface=concrete_plates")
    (556,"shop=copyshop")
    (557,"surface=paving_stones_30")
    (558,"surface=interlock")
    (559,"access=hov")
    (560,"highway=elevator")
    ;
/*
    (0,"boundary=local_authority")
    (0,"man_made=communications_tower")
    (0,"shop=deli")
    (0,"barrier=turnstile")
    (0,"building=offices")
    (0,"building=bunker")
    (0,"natural=stone")
    (0,"railway=railway_crossing")
    (0,"leisure=dog_park")
    (0,"building=semi_detached")
    (0,"man_made=watermill")
    (0,"route=trolleybus")
    (0,"admin_level=3")
    (0,"building=block")
    (0,"barrier=guard_rail")
    (0,"bicycle=unknown")
    (0,"highway=abandoned")
    (0,"surface=dirt_sand")
    (0,"barrier=chain")
    (0,"barrier=bump_gate")
    (0,"building=residental")
    (0,"surface=cement")
    (0,"man_made=embankment")
    (0,"building=ruins")
    (0,"highway=incline")
    (0,"abutters=commercial")
    (0,"barrier=hampshire_gate")
    (0,"shop=music")
    (0,"shop=funeral_directors")
    (0,"wetland=mangrove")
    (0,"place=borough")
    (0,"building=apartment")
    (0,"boundary=census")
    (0,"barrier=kerb")
    (0,"building=glasshouse")
    (0,"aeroway=holding_position")
    (0,"shop=general")
    (0,"building=tank")
    (0,"railway=monorail")
    (0,"service=parking")
    (0,"place=state")
    (0,"railway=proposed")
    (0,"shop=art")
    (0,"natural=hill")
    (0,"railway=turntable")
    (0,"tourism=cabin")
    (0,"shop=photo")
    (0,"boundary=lot")
    (0,"shop=fishmonger")
    (0,"amenity=clinic")
    (0,"boundary=political")
    (0,"man_made=well")
    (0,"highway=byway")
    (0,"leisure=horse_riding")
    (0,"service=bus")
    (0,"building=tower")
    (0,"entrance=service")
    (0,"shop=fabric")
    (0,"railway=miniature")
    (0,"abutters=mixed")
    (0,"surface=stone")
    (0,"access=emergency")
    (0,"landuse=mine")
    (0,"amenity=shower")
    (0,"waterway=lock")
    (0,"area=yes")
    ;
*/

boost::optional<tag_type> tag_from_name(name_type const& name)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
    if (right_iter != tag_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    return tag;
}

boost::optional<tag_type> tag_value_from_name(name_type const& name, std::string const& val)
{
    boost::optional<tag_type> tag;
    tag_lookup_type::right_const_iterator right_iter = tag_value_lookup.right.find(name+"="+val);
    if (right_iter != tag_value_lookup.right.end())
    {
        tag.reset(right_iter->second);
    }
    else
    {
        tag_lookup_type::right_const_iterator right_iter = tag_lookup.right.find(name);
        if (right_iter != tag_lookup.right.end())
        {
            tag.reset(1024 + right_iter->second);
        }
    }
    return tag;
}


}}
